### ISSUE TITLE
How to train ldm use image as conditon?

### ISSUE THREAD

**Issue by Allencheng97** [CompVis/latent-diffusion#161]
I use the  Frozenclip image embedder try to train ldm use image as conditional key.  The out put of cond model is batch*512 size.But I tried  concat and crossattn, it failed since x has 4 dimension and condition vector are 2 dimension. How can I solve this ?  Is there anyone success could share your script?

**Comment by pokameng** [comment]
I use the Frozenclip image embedder try to train ldm use image as conditional key. The out put of cond model is batch*512 size.But I tried concat and crossattn, it failed since x has 4 dimension and condition vector are 2 dimension. How can I solve this ? Is there anyone success could share your script?
@Allencheng97 @asanakoy @pesser @crowsonkb @theRealSuperMario

**Comment by PedestrianZQZ** [comment]
hi @Allencheng97 i'm having the same problem, did you find any solution?

**Comment by zhanchao019** [comment]
> 

any solution QAQ, facing same problem

**Comment by QiuhongAnnaWei** [comment]
Any updates on this?
