### ISSUE TITLE
Reproducing inpainting results

### ISSUE THREAD

**Issue by SirWyver** [CompVis/latent-diffusion#44]
Hi, 
thanks for this great repo! I was trying to reproduce the inpainting results on the example images and obtain noticeable artifacts. 
![image](https://user-images.githubusercontent.com/19650385/163187837-655c16bb-ed95-4c3c-a625-4c6d5677bc58.png)
![image](https://user-images.githubusercontent.com/19650385/163188105-cc25a757-8fa5-444b-a912-77f0162ccf5c.png)

Do you have an idea what could be the reason? I am running:
`python scripts/inpaint.py --indir data/inpainting_examples/ --outdir outputs/inpainting_results `

**Comment by windj007** [comment]
I'm facing this issue too! I haven't yet figured out what's wrong...

**Comment by windj007** [comment]
Currently it seems to me that the default value for `--steps` is too small (=50). In Appendix D, Table 14 the authors report that they use 1000 steps (row "Diffusion steps"). Do I understand the meaning of this parameter correctly?

**Comment by windj007** [comment]
I've just tried to predict with --steps 500 and it outputs images with severe artifacts, sometimes better than --steps 50, sometimes worse - but very far from the images in paper.

**Comment by windj007** [comment]
An example image, predictions by different models, 4th and 5th images are from LDM

![brock-wegner-uvZGlOgeW1U-unsplash_crop000_mask000](https://user-images.githubusercontent.com/890224/163268360-2d9100f5-cc41-48db-b894-a2410624e3ba.png)

**Comment by windj007** [comment]
Btw, it does not allow to set more than 500 steps - when I set 501 it throws an error:

```
Traceback (most recent call last):
  File "/home/user/project/inpaint-modified.py", line 86, in <module>
    samples_ddim, _ = sampler.sample(S=opt.steps,
  File "/home/user/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/project/ldm/models/diffusion/ddim.py", line 89, in sample
    self.make_schedule(ddim_num_steps=S, ddim_eta=eta, verbose=verbose)
  File "/home/user/project/ldm/models/diffusion/ddim.py", line 43, in make_schedule
    ddim_sigmas, ddim_alphas, ddim_alphas_prev = make_ddim_sampling_parameters(alphacums=alphas_cumprod.cpu(),
  File "/home/user/project/ldm/modules/diffusionmodules/util.py", line 65, in make_ddim_sampling_parameters
    alphas = alphacums[ddim_timesteps]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000
```

PS. Sorry for lots of separate messages, I will not spam anymore

**Comment by rromb** [comment]
Hi, thanks for catching this! With the latest release of the text-to-image model there was a bug always setting `num_heads=1` for the inpainting model (which uses `num_heads=8` and which was therefore simply ignored). Should be fixed with 71ebe4079163a60d932646f23c1b03f99d610c57 (and should also work with the latest commit just before the txt2img release, i.e. f13bf9bf463d95b5a16aeadd2b02abde31f769f8). 

Running `python scripts/inpaint.py --indir data/inpainting_examples/ --outdir outputs/inpainting_results` now produces these results:
![bertrand-gabioud-CpuFzIsHYJ0](https://user-images.githubusercontent.com/38811725/163589849-9d161028-d9d2-4f28-8364-919bff444e13.png)
![photo-1583445095369-9c651e7e5d34](https://user-images.githubusercontent.com/38811725/163589877-c06872e0-bd88-4376-93c2-cb060eedb99e.png)

**Comment by windj007** [comment]
Thank you for such a quick response! I'll update the code and check the generation.

**Comment by windj007** [comment]
I've checked the generation and confirm that the problem has gone.
